# Generated by Django 4.1.1 on 2022-10-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jio',
            fields=[
                ('monthly_rental', models.CharField(max_length=264, primary_key=True, serialize=False, unique=True)),
                ('pack_validity', models.CharField(max_length=264)),
                ('total_data', models.CharField(max_length=264)),
                ('family_plan', models.CharField(max_length=264)),
                ('data_with_rollover', models.CharField(max_length=264)),
                ('sms_per_day', models.CharField(max_length=264)),
                ('voice_call', models.CharField(max_length=264)),
            ],
        ),
    ]
