# Generated by Django 4.1.1 on 2022-10-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jio',
            name='amazon_prime',
            field=models.CharField(default='NO', max_length=264),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jio',
            name='jio_cloud',
            field=models.CharField(default='NO', max_length=264),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jio',
            name='jio_security',
            field=models.CharField(default='NO', max_length=264),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jio',
            name='jio_tv',
            field=models.CharField(default='NO', max_length=264),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jio',
            name='netflix_mobile',
            field=models.CharField(default='NO', max_length=264),
            preserve_default=False,
        ),
    ]
