# Generated by Django 4.1.1 on 2022-09-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airtel',
            name='id',
        ),
        migrations.AlterField(
            model_name='airtel',
            name='monthly_rental',
            field=models.CharField(max_length=264, primary_key=True, serialize=False, unique=True),
        ),
    ]
